Style/cafe map
anniversaryArchive/archive pull request #40
Opened 2024-02-02 05:53 UTC by kimsojung318

### ✨ 수정 사항
1. 검색 필터 `BottomDialog` 추가
2. 선택한 멤버 영역 추가 (스크롤)

### 👊 추후에 수정 사항
1. 하단 `BottomDialog` 영역
2. 검색 필터 `지역 번호` 항목 추가

### 🖥️ 화면(.gif)
![Vite + Vue + TS - Chrome 2024-02-02 14-49-53](https://github.com/anniversaryArchive/archive/assets/68046496/37bcf5d5-1e1f-498f-9cd6-83b75d7345a0)

2024-02-08 14:45 UTC, hyejin-1010 requested changes
고생하셨습니다 .ᐟ.ᐟ 🙇‍♀️
Comment 몇 개 달았는데, 다른 것들은 그냥 참고만 하시고 넘기시면 됩니당.
🚨 이모티콘이랑 같이 단거는 기능적 이슈여서, 해당 커멘트들만 확인하고 수정 부탁드립니다 .ᐟ.ᐟ

2024-02-08 14:45 UTC, hyejin-1010 commented on src/assets/images/icon/filter-icon.png
탭 아이콘은 `svg`로 변경하셨는데, 필터 아이콘은 `png`로 추가하시는 이유가 따로 있으신걸까요??
그냥 궁금해서 여쭤봅니다 .ᐟ.ᐟ

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +      <q-input he outlined v-model="groupData.name" disable>
이거 `he`는 무슨 역할인가요??

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +          <q-avatar>
`q-input`에 `disable` 영향으로 avatar에도 `opacity: 0.6`이 먹혀있는데 의도하신건가요?? 혹시 몰라 여쭤봅니다.ᐟ

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +          <select-box
🚨
1. 아티스트 선택 후, 검색 버튼 클릭
2. 다시 필터 버튼을 통해 팝업 열기

위  동작을 통해 팝업을 열면, 팝업 내 아티스트 선택 Input 박스가 비어져있습니다 .ᐟ 
* 정상적인 동작: 직전에 선택한 아티스트가 선택되어 있는 상태이어야 함. 

해당 부분 확인 부탁드립니다 🙇‍♀️

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
🚨 `npm run build` 명령어를 통해 빌드를 해보면, typescript checker를 통해 `cafeMap` 화면에서 에러가 발생합니다.ᐟ
해당 부분들 확인 부탁드립니다 🙇‍♀️

<img width="711" alt="스크린샷 2024-02-08 오후 11 15 04" src="https://github.com/anniversaryArchive/archive/assets/31975198/1a3fc3ff-e8bc-43a4-bcea-35df6ec6b7fb">

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +    const groupData = ref({} as Group[]);
**💬 참고** 
타입스크립트에서는 **타입 단언**(`as Group[]`)은 적게 쓰는 것이 코드 퀄리티에 좋다고 합니다!

`const groupData: Ref<Group[]> = ref([]);` 이런 방식 혹은 다른 식으로 하면 타입 단언을 안쓸 수도 있습니다.ᐟ 참고해주세요 🙇‍♀️

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +    function resetFunc(type: Boolean) {
**💬 참고**
boolean(primitive type)과 Boolean(reference type)은 다른 타입인데, 특수한 경우가 아니라면 reference type을 사용하는 것을 지양하고 있습니다.ᐟ 참고하시면 좋을 거 같아 코멘트 남겨둡니다 :)

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +    function resetFunc(type: Boolean) {
💬 지극히 개인적인 의견 

파라미터가 `boolean` 타입인데, 변수명은 `type`인게 직관적이지 않은 거 같습니당 
`needReset`, `shouldReset`, `showConfirm` 등등 
역할을 담은 단어를 쓰면 더 좋지 않을 까 하는 생각이 들어 코멘트만 남겨둡니다.ᐟ 지극히 개인적인 의견이니 무시하셔도 됩니다 .ᐟ.ᐟ

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +        Object.entries(selectList).forEach(([, item]) => {
`selectList`의 type이 `array`인데, 
```
selectList.forEach((item) => {
```
형식이 아니라 `Object.entries` 로 다시 가공해서 value만 뽑아쓰시는 이유가 따로 있으실까요?? 
그냥 궁금해서 여쭤봅니당 .ᐟ

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
>          artistListSave.push(val);
`artistListSave` 변수는 쓰이는 곳이 없는 거 같은데, 혹시 무슨 역할일까요??

2024-02-08 14:45 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
>      function searchData() {
해당 함수는
```
function searchData() {
      artistNameList.value = artistList.value.reduce((acc, artist) => {
        // 선택된 artist 객체를 찾는다.
        const selectedArtist = selectBoxOptions.value.artist.data.find(({ id }) => artist.id === id);
        if (selectedArtist) acc.push(selectedArtist.label);
        return acc;
      }, []);

      getArchives();
    }
``` 
요런 느낌으로 짜는 것도 괜찮을 거 같아요~.ᐟ 
그냥 코드 스타일 공유 겸 달아놓습니당

2024-02-19 12:21 UTC, kimsojung318 commented on src/assets/images/icon/filter-icon.png
아뇨.. 없습니다.. 그냥 잊은 거 같아요...
파일 변경해두겠습니다!

2024-02-19 12:29 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +      <q-input he outlined v-model="groupData.name" disable>
오타 같은데 오류가 안 나는 게 신기하네요...
수정하겠습니다!

2024-02-19 12:37 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +          <q-avatar>
수정하겠습니다!

2024-02-19 12:38 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +          <select-box
다시 검색 필터 오픈 시 기존 선택이 리셋 되어야 한다고 생각해서 비어두었습니다.
다시 수정하겠습니다!

2024-02-19 12:53 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +    function resetFunc(type: Boolean) {
검색 후 필터 영역 데이터 리셋을 위해 추가한 코드라 위에 내용 반영하면서 필요가 없어서 삭제 했습니다! 내용은 이후 개발 시 참고 하겠습니다!

2024-02-19 12:53 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +    function resetFunc(type: Boolean) {
검색 후 필터 영역 데이터 리셋을 위해 추가한 코드라 위에 내용 반영하면서 필요가 없어서 삭제 했습니다! 내용은 이후 개발 시 참고 하겠습니다!

2024-02-20 12:17 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +    const groupData = ref({} as Group[]);
참고하겠습니다!

2024-02-20 12:22 UTC, kimsojung318 commented on src/pages/cafeMap.vue
>          artistListSave.push(val);
검색 필터에서 선택한 아티스트 목록을 카페 목록 상단에 해시태그 형식으로 노출하고 있습니다~!

2024-02-20 13:13 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +        Object.entries(selectList).forEach(([, item]) => {
없습니다. 수정했습니다~!

2024-03-01 04:59 UTC, hyejin-1010 requested changes
`resolve` 된 것들은 확인했습니다!
코멘트 하나 더 단거랑, 아직 resolve 안 된 것들 확인해주세요!

2024-03-01 04:59 UTC, hyejin-1010 commented on src/pages/cafeMap.vue
> +      <q-input outlined v-model="groupData.name" readonly>
해당 부분 에러나네욤, 확인 부탁드려요~!

<img width="497" alt="image" src="https://github.com/anniversaryArchive/archive/assets/31975198/937a0b34-1a7e-4ffc-babd-0e3260db49f2">

2024-03-14 02:46 UTC, kimsojung318 commented on src/pages/cafeMap.vue
> +      <q-input outlined v-model="groupData.name" readonly>
해당 부분 수정했습니다!

2024-04-24 13:56 UTC, hyejin-1010 approved these changes
수고하셨습니다.ᐟ

2024-04-24 13:56 UTC, merged